version: '3'
services:
  webpack:
    build: ./docker
    volumes:
      - ./src:/webpack_practice/src
      - ./markup/assets:/webpack_practice/markup/assets
      - ./docker/package.json:/webpack_practice/package.json
      - ./docker/webpack.config.js:/webpack_practice/webpack.config.js
    command: yarn watch
    ports:
      - 2000:2000