FROM node:13.8.0
WORKDIR /webpack_practice
RUN yarn init -y && \
  yarn add -D webpack webpack-cli webpack-dev-server babel-loader @babel/core @babel/preset-env node-sass sass-loader style-loader css-loader